### ISSUE TITLE
Bug in task up-to-date status

### ISSUE THREAD

**Issue by vic-cw** [michel-kraemer/gradle-download-task#105] opened 2018-01-17 21:03 UTC
I can't seem to find why, but it seems that when using `overwrite false`, there is a strange and apparently random behavior.

Sometimes, a task starts appearing as up to date, even if the destination file has been deleted. What is really weird is that I was able to get to a point where two different tasks with the exact same code had different behaviors : one was correctly noticing that it was out of date, while the other wasn't.

I tried killing the gradle daemon and retrying, to no avail.

For lack of a better identification, here is [the screen recording of that behavior](https://drive.google.com/file/d/15FBIKYO7xmZ9go2ZA4sc7eBqav1efUpt/view?usp=sharing).

Here is the gradle build file I used :

```
plugins {
	id "de.undercouch.download" version "3.3.0"
}

import de.undercouch.gradle.tasks.download.Download

String url = "https://www.google.fr/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png";

task cacheFolderDownload (type: Download) {
	src url
	dest (System.getProperty("user.home") + "/Documents/temp/build")
	overwrite false
}

task userHomeHiddenFolderDownload (type: Download) {
	src url
	dest (System.getProperty("user.home") + "/.hidden")
	overwrite false
}

task userHomeDownload (type: Download) {
	src url
	dest (System.getProperty("user.home"))
	overwrite false
}

task buildDirRelativeToUserHomeDownload (type: Download){
	src url
	dest (System.getProperty("user.home") + "/Documents/temp/build")
	overwrite false
}

task absoluteBuildDirPathTask (type: Download) {
	src "https://www.google.fr/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
	dest "/Users/Vic/Documents/temp/build"
	overwrite false
}

task workingDownloadTask (type: Download) {
	src url
	dest buildDir
	overwrite false
}
```

**Comment by michel-kraemer** [comment] 2018-03-03 14:33
Thanks for reporting the issue. However, I cannot reproduce it on my computer. I've watched your screencast and I can see there seems to be a problem on your machine, but everything works as expected here.

The issue is a couple of weeks old. Are you still experiencing this strange behaviour?

**Comment by michel-kraemer** [comment] 2018-03-03 15:06
By the way, which Gradle version are you using?

**Comment by vic-cw** [comment] 2018-03-05 08:03
Hi Michael,

I am using Gradle 4.4.1.

I can't confirm whether I am still experiencing the issue, since I worked around it, but I don't see a reason why it would have changed.

Hope we can reproduce it

**Comment by michel-kraemer** [comment] 2018-03-10 16:03
Thanks for the feedback. Without being able to reproduce the issue, it will be hard to fix it. I'm closing this one here and we'll continue the discussion in #96.

**Closed by michel-kraemer** 2018-03-10 16:03 UTC
Labels: feedback-required
