### ISSUE TITLE
"Could not get unknown property 'Download'" error trying to use this plugin

### ISSUE THREAD

**Issue by mikesnare** [michel-kraemer/gradle-download-task#75] opened 2017-01-30 22:05 UTC
I've tried both the latest gradle syntax and the older style to try to apply this plugin, and no matter what I keep getting the same output:

> A problem occurred evaluating root project 'root'.
> Could not get unknown property 'Download' for root project 'root' of type org.gradle.api.Project.

Importing the class doesn't help, nor does specifying the class using the fully qualified class name as the type.

If I create a basic task and use the doLast syntax it seems to work, but I'd prefer to the use the `type: Download` syntax.

I've got several other plugins in use, and this is the only one that has this problem.  Any thoughts?

**Comment by mikesnare** [comment] 2017-01-30 22:21
A little more....

If I add the plugin to the plugins block of my root project AND add the task to the root project as well, it works.  But I need this plugin in a child project in a multi-project build.  More specifically, I need it inside an applied file that does deployment work:

The root project includes the app project, and the app.gradle build file calls 'apply deploy.gradle' to bring in deployment logic.  It's in this deploy.gradle file that I want to use this plugin, but no configuration I can find will make that work.

I've tried placing the plugin in the plugins block of both the root and app projects, and then I've tried placing the import of the Download class in every level of the build I can, and I either get the issue with Download not being a property of the project, or I get an error telling me it can't resolve org.de.undercouch.gradle.tasks.download.Download.

**Comment by michel-kraemer** [comment] 2017-01-31 06:04
It's hard to say what the problem is here. Would it be possible to provide a small example build where the error happens? This would help a lot.

If your build is too complex to create such an example then you're probably running into a similar problem as others: https://github.com/michel-kraemer/gradle-download-task/issues/48. The issue's title is misleading, but I think it's the same problem.

If it's the same problem then I'm afraid there's nothing we can do at the side of gradle-download-task. It seems to be a bug in Gradle or some kind of unfortunate combination of plugins and configuration that causes the problem. Maybe it would make sense to contact the Gradle people in this case.

**Comment by mikesnare** [comment] 2017-01-31 13:03
Done: https://github.com/mikesnare/download-bug

That's a very simple project that demonstrates the issue.  It seems that the plugin can only be applied at one level of a multi-build project hierarchy, and can only be used directly in that one project.  It can never be used inside a gradle file that is included in the build using `apply from: someFile.gradle`

FWIW, I have no issues using any other plugin at all levels of my multi-project build when I include the plugin at the root level, and no other plugin requires that I import the task class explicitly.  Applying them makes them available immediately, and at any level of the project.

I've looked at a couple other plugins I'm using that work, and they each register themselves *NOT* in the project extensions, but in the project extensions' extraProperties.  extraProperties are made available to child projects and included scripts where the extensions themselves may not be (not sure, TBH).

In the plugin code:

```groovy
@Override
void apply(Project project) {
  project.extensions.extraProperties.set(SomePluginClass.getSimpleName(), SomePluginClass)
}
```

This may break the ability to do this using the project dsl (not sure if the same plugin could be registered a second time in the ext props or what...):

```groovy
task someTask {
  doLast {
    download {
      ...
    }
  }
}
```

But for my money that seems to be a small price to pay to get this working correctly in multi-project builds and included scripts.

**Comment by michel-kraemer** [comment] 2017-02-13 11:59
Thanks for the small test project. I played around with it a bit and there is a very easy solution. Please have a look at the following gist which contains a patch for your project that will make it work:
https://gist.github.com/michel-kraemer/8206d20e7b9c413348afe0366c98fbff

To summarize, add `import de.undercouch.gradle.tasks.download.Download` to your child project's build file and add a `buildscript` block to your `fragment.gradle` file. The latter is necessary because `plugin` blocks are not allowed there. I played around with other plugins and it seems Gradle does not allow you to use plugins in files that you include with `apply from` unless you specify the plugin dependency in the included files too. So this is by design and no bug.

On the other hand I totally agree with you that the fact that you have to import `de.undercouch.gradle.tasks.download.Download` is cumbersome when all other plugins don't require you to do that. This is something that needs to be fixed. It is a breaking change though and - since I'm using semantic versioning for this plugin - I can only do it in the upcoming 4.0.0. I will open a new issue for that so we can keep track of it.

I hope this helps. I think it should solve your problem, so I'm closing this issue. If I'm wrong and the problem persists or if you have another question feel free to reopen the issue again!

Cheers,
Michel

**Comment by mikesnare** [comment] 2017-02-13 14:12
Thanks for taking a look.  I think there may be an even easier way.  It seems to be working for me.

In the root project's build.gradle:

```groovy
// Register the plugin at the root level
plugins {
    id 'de.undercouch.download' version '3.2.0'
}

// Make it available everywhere via the project ext:
ext {
    Download = de.undercouch.gradle.tasks.download.Download
    download = download
}
```

With that, the following seems to be valid anywhere without any additional code, even in files that are applied from child projects:

```groovy
task googleViaType(type: Download) {
    src 'http://www.google.com'
    dest buildDir
}

task googleViaDSL {
    doLast {
        download {
            src 'http://www.google.com'
            dest buildDir
        }
    }
}
```

FWIW, I don't think you need to change where your Download class is packaged, you just need to make it available by adding it to the ext of the project that added it.  If your plugin did that in code, then the ext code I've shown wouldn't be necessary.  Just register the plugin and use it anywhere.

**Comment by michel-kraemer** [comment] 2017-02-13 19:10
> FWIW, I don't think you need to change where your Download class is packaged, you just need to make it available by adding it to the ext of the project that added it. If your plugin did that in code, then the ext code I've shown wouldn't be necessary. Just register the plugin and use it anywhere.

Sounds interesting. You said you've seen this in other plugins. Can you tell me which ones you mean?

I'll reopen the issue because I'm interested in how this idea will turn out. Sorry for closing it too quickly.

**Comment by mikesnare** [comment] 2017-02-13 20:01
The node plugin has it: https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/NodePlugin.groovy#L64

As does the React plugin: https://github.com/ehirsch/gradle-react-plugin/blob/master/src/main/groovy/net/eikehirsch/gradle/react/ReactPlugin.groovy#L39

To be fair, I don't know that it's *the* prescribed mechanism for this -- it may well not be.  I've just not had to do something like this with any other plugin I've used until now.

Thanks again for looking into it.

**Comment by michel-kraemer** [comment] 2017-04-23 10:14
I just pushed a commit that makes the task available as extra property as you suggested. I also uploaded a new snapshot. You can test it if you like. Feedback would be appreciated.

**Comment by DethRaid** [comment] 2017-06-23 03:16
I'd just like to say that I've also run into this issue, and it was solved by adding the `ext` block to my `build.gradle` file. Do you think you could add something about the workaround to the README?

**Comment by TomDmitriev** [comment] 2017-07-13 08:19
```groovy
import de.undercouch.gradle.tasks.download.Download
```

This has solved the problem in my case.

**Closed** 2018-03-03 11:41 UTC

**Comment by michel-kraemer** [comment] 2018-03-03 12:09
A fix for this will be in the next version.

**Comment by amimas** [comment] 2018-03-21 15:03
Is there an outlook on when the next version will be released?

**Comment by michel-kraemer** [comment] 2018-03-21 15:07
It has already been released two weeks ago. Version 3.4.2 has this feature. If it doesn't work for you, please open a new issue.

**Comment by ohinteresting** [comment] 2023-09-22 07:31
> I've tried both the latest gradle syntax and the older style to try to apply this plugin, and no matter what I keep getting the same output:
> 
> > A problem occurred evaluating root project 'root'.
> > Could not get unknown property 'Download' for root project 'root' of type org.gradle.api.Project.
> 
> Importing the class doesn't help, nor does specifying the class using the fully qualified class name as the type.
> 
> If I create a basic task and use the doLast syntax it seems to work, but I'd prefer to the use the `type: Download` syntax.
> 
> I've got several other plugins in use, and this is the only one that has this problem. Any thoughts?
you just need "apply plugin: 'de.undercouch.download'" in your build.gradle.
