### ISSUE TITLE
Download dest with relative path string values download to location relative to cwd instead of project

### ISSUE THREAD

**Issue by jeremymailen** [michel-kraemer/gradle-download-task#26] opened 2015-05-11 05:50 UTC
Repro example:
https://drive.google.com/file/d/0Bz0ngyBOy9UyNXhBY2J3ci03cG8/view?usp=sharing
cd download-path-issue
gradle download-project:download
(the file is downloaded to the project root directory)
cd download-project && gradle download
(the file is downloaded to the project directory)

**Comment by michel-kraemer** [comment] 2015-05-13 05:49
Thanks for the reproducer. I'm a little bit confused, because your code behaves exactly like I would have expected it. You specify a relative path in your `download` task and it seems to me this path is relative to the current working directory (which makes sense to me). If I specify `dest "${projectDir}/apache-2.0-license.txt"` instead, it writes the file to the project directory.

I'm not really sure how other Gradle task types work. Do you know an example where a task writes to a directory that is relative to the project directory and not relative to the current working directory?

Cheers,
Michel

**Comment by michel-kraemer** [comment] 2015-05-13 05:54
Oh, I see. The copy task writes to a directory relative to the project:

```
task copy(type: Copy) {
    from "/home/mkraemer/test.txt"
    into "."
}
```

That's good to know. Your fix is indeed valid! Thanks a lot!

I'm wondering if anyone relies on the current behavior of gradle-download-task. I hope not.

Cheers,
Michel

**Comment by jeremymailen** [comment] 2015-05-13 06:49
Yes, I think your observation is correct and that, in general, standard gradle tasks treat relative string paths as relative to the project they are part of.  This enables them to behave consistently when executed from different directories within a multi-module build.

**Comment by michel-kraemer** [comment] 2015-08-19 10:53
The change will be in the new version that will be released today. I'm going to close this issue now.

**Closed by michel-kraemer** 2015-08-19 10:53 UTC
