### ISSUE TITLE
Gradle 2.14 break

### ISSUE THREAD

**Issue by zaiddag** [michel-kraemer/gradle-download-task#49] opened 2016-06-22 01:39 UTC
ProgressLogger doesn't exist in the same class path (moved to gradle.internal) which I don't think is even importable anymore. Should probable just ditch ProgressLogger all together as of 2.14

**Comment by michel-kraemer** [comment] 2016-06-22 05:39
Thanks I'll look into this.

Possible duplicate of #47

**Comment by zaiddag** [comment] 2016-06-22 08:27
@michel-kraemer per the gradle guide, looks like we should be using the slf4j logger:

You can also hook into Gradle's logging system from within other classes used in the build (classes from the buildSrc directory for example). Simply use an SLF4J logger. You can use this logger the same way as you use the provided logger in the build script.

```
import org.slf4j.Logger
import org.slf4j.LoggerFactory

Logger slf4jLogger = LoggerFactory.getLogger('some-logger')
slf4jLogger.info('An info log message logged using SLF4j')
```

https://docs.gradle.org/current/userguide/logging.html

There also appears to be a logger available from org.gradle.api which may be of more use:

https://docs.gradle.org/current/javadoc/org/gradle/api/logging/package-summary.html

Particularly logger:

```
An extension to the SLF4J Logger interface, which adds the quiet and lifecycle log levels.

You can obtain a Logger instance using Logging.getLogger(Class) or Logging.getLogger(String). A Logger instance is also available through Project.getLogger(), Task.getLogger() and Script.getLogger().

```

**Comment by michel-kraemer** [comment] 2016-06-25 11:19
I uploaded a new snapshot that should fix the issue. May I ask you to test it, so I can release a new version of the plugin?

Please use the following to apply the snapshot:

```gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.1.0-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

Remove the plugin from your `plugin` section in the build file.

Thanks for your support!

**Comment by gesellix** [comment] 2016-06-27 12:37
I can confirm that this change fixes my issue. How fast could you make a release?

**Comment by michel-kraemer** [comment] 2016-06-27 15:04
> How fast could you make a release?

I'm out of office until Friday. Sorry. Do you need it urgently or can you work with the snapshot for the time being?

**Comment by gesellix** [comment] 2016-06-27 15:25
@michel-kraemer no pressure, it's not that urgent. Thanks for the quick feedback!

**Comment by michel-kraemer** [comment] 2016-06-28 18:31
OK. Then I'll do it on the weekend, unless I find another issue (maybe related to #48).

**Comment by gesellix** [comment] 2016-06-28 18:47
Fine for me, I can rely on a snapshot meanwhile.

**Comment by michel-kraemer** [comment] 2016-07-03 09:09
Thanks. I'll release a new version in the next couple of days. I'm going to close this issue now.

**Closed by michel-kraemer** 2016-07-03 09:09 UTC
Labels: duplicate

**Comment by gesellix** [comment] 2016-07-03 09:25
👍
