### ISSUE TITLE
http.nonProxyHosts system property ignored

### ISSUE THREAD

**Issue by Ithildir** [michel-kraemer/gradle-download-task#62] opened 2016-09-23 20:29 UTC
Hi,

It seems the plugin ignores the properties `http.nonProxyHosts` and `https.nonProxyHosts`.

For example, I get a `HttpHostConnectException` if I try to download a file from Google and I pass non-existent proxy settings, while ignoring `*.google.com` at the same time:

```
gradle downloadFile -Dhttp.proxyHost=localhost -Dhttp.proxyPort=999 -Dhttp.nonProxyHosts=*.google.com -Dhttps.nonProxyHosts=*.google.com
```

Thanks!

**Comment by michel-kraemer** [comment] 2016-09-23 20:38
Yes, I can confirm this. Thanks for reporting.

I'll try to implement this feature when I've got some time, but it might take a couple of days/weeks. Pull requests are very appreciated :-)

**Comment by Ithildir** [comment] 2016-09-23 20:42
Yeah, I'm already starting to fiddle around with the code. I'm not a very big expert on HttpClient, but hopefully I'll have something to send you for review soon :blush:

**Comment by michel-kraemer** [comment] 2016-10-03 09:21
I'm closing this one in favour of #63.

**Closed by michel-kraemer** 2016-10-03 09:21 UTC
Labels: enhancement

**Comment by timotei** [comment] 2017-02-08 13:39
@michel-kraemer I think we should keep this open as #63 seems to be closed :(

**Comment by michel-kraemer** [comment] 2017-02-09 15:46
@timotei What do you mean? There was a pull request #68 which has been merged. So both issues can be closed now. If you have a problem related to this feature please open a new issue.

**Comment by michel-kraemer** [comment] 2017-02-09 15:47
Sorry. I meant #72. This was the PR that was merged at the end.

**Comment by timotei** [comment] 2017-02-09 21:36
@michel-kraemer Oh. OK. I haven't seen anywhere the link to #72, that's why I was confused. 

Thanks for the clarification!
