### ISSUE TITLE
task is not considered UP-TO-DATE when onlyIfModified == true && overwrite == false

### ISSUE THREAD

**Issue by scr** [michel-kraemer/gradle-download-task#84] opened 2017-05-05 04:11 UTC
This up-to-date check is backwards - when onlyIfModified is true, then it will never be up-to-date.

It should be possible to set onlyIfModified = true and overwrite = false and only download if the files are newer, but that doesn't seem to work in the current state.

```
        getOutputs().upToDateWhen(new Spec<Task>() {
            @Override
            public boolean isSatisfiedBy(Task task) {
                return !(isOnlyIfModified() || isOverwrite());
            }
        });
```

**Comment by michel-kraemer** [comment] 2018-03-03 13:58
I cannot reproduce this. I tried the following combinations:

File does not exist:

onlyIfModified | overwrite | up-to-date
-- | -- | --
false | false | false
true | false | false
false | true | false
true | true | false

File exists and is up to date (i.e. not older than on the server):

onlyIfModified | overwrite | up-to-date
-- | -- | --
false | false | true
true | false | true
false | true | false
true | true | true

File exists and is not up to date (i.e. older than on the server):

onlyIfModified | overwrite | up-to-date
-- | -- | --
false | false | true
true | false | true
false | true | false
true | true | false

As far as I can tell, everything is correct. You are suggesting that if `onlyIfModified` equals `true` and `overwrite` equals `false` and the file exists, but is too old, it should still be downloaded (i.e. `up-to-date` should be `false`). However, that would mean the file is overwritten although `overwrite` is `false`. This is not the intended behaviour.

I'm closing this issue. If you have any other concerns or if I misunderstood you somehow, feel free to reopen it.

**Closed by michel-kraemer** 2018-03-03 13:58 UTC

**Comment by lweb20** [comment] 2019-02-12 00:19
Same here with gradle 5.2 and 4.10
